name: segregation
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pandas
  - geopandas>=0.9
  - matplotlib
  - scikit-learn
  - seaborn
  - numpy
  - scipy
  - descartes
  - pip
  - libpysal
  - tqdm
  - mapclassify
  - pygeos
  - joblib