name: segregation
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - geopandas
  - matplotlib
  - scikit-learn
  - seaborn
  - numpy
  - scipy
  - pip
  - pip:
    - git+git://github.com/pysal/libpysal.git
